"""scripts/triage_s4_rerun.py — Deterministic local triage tool for S4 rerun artifacts.

Usage:
    python scripts/triage_s4_rerun.py --artifacts-dir <DIR> [--json] [--markdown <PATH>]

This tool reads artifacts downloaded after a paid-credit S4 rerun and classifies
the pipeline stage reached, adoption gate result, and recommended next action.

Safety constraints:
  - No network access of any kind.
  - data/api_usage_ledger.json and all frozen files are never written.
  - ALL dynamic strings in output pass through _safe_text() to suppress secrets.
  - Malformed fitness_report.json is fail-closed as tool_failure.
  - malformed mutation_patch.json is classified as propose_failed (patch not produced).
  - promote_eligible never triggers promotion; it requires_owner_approval=true.

Artifact directory layout:
  Both flat and subdirectory layouts are supported.  Flat takes priority.

  Flat layout (preferred):
    <artifacts_dir>/mutation_patch.json
    <artifacts_dir>/api_usage_ledger.json
    <artifacts_dir>/candidate_detector.py
    <artifacts_dir>/fitness_report.json

  Subdirectory layout (fallback, used when flat file not found):
    <artifacts_dir>/mutation-patch/mutation_patch.json
    <artifacts_dir>/api-usage-ledger/api_usage_ledger.json
    <artifacts_dir>/candidate-detector/candidate_detector.py
    <artifacts_dir>/fitness-report/fitness_report.json

fitness_report.json format:
  Both flat and evaluator-wrapper shapes are supported:
    Flat:    {"passed_adoption_gate": bool, "score": float, ...}
    Wrapper: {"success": bool, "passed_adoption_gate": bool,
              "fitness_report": {"passed_adoption_gate": bool, "score": float, ...}, ...}

  The wrapper shape matches evaluate_candidate.py's _write_report() output.
  Normalisation uses the nested "fitness_report" dict when present (it contains
  the full core.fitness metrics); otherwise falls back to the outer dict.

promote_result.json:
  This file is NOT generated by the current immunization_loop.yml workflow.
  The "promoted" classification is reserved for a future workflow that emits
  this artifact.  Its presence is detected but it will not appear in the
  standard per-outcome triage for current runs.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Schema version for the output format
# ---------------------------------------------------------------------------
_SCHEMA_VERSION = 1

# ---------------------------------------------------------------------------
# Secret-detection heuristics (conservative; never emit the matched value)
# ---------------------------------------------------------------------------
_SECRET_PATTERNS = [
    re.compile(r"(?i)AIza[0-9A-Za-z\-_]{35}"),         # Google API key
    re.compile(r"(?i)GEMINI_API_KEY\s*[=:]\s*\S+"),     # explicit assignment
    re.compile(r"(?i)Authorization\s*:\s*\S+"),           # auth header
    re.compile(r"(?i)Bearer\s+[A-Za-z0-9\-._~+/]+=*"),  # bearer token
    re.compile(r"(?i)password\s*[=:]\s*\S{8,}"),         # password assignment
    re.compile(r"(?i)secret\s*[=:]\s*\S{8,}"),           # secret assignment
]

_SECRET_REPLACEMENT = "[SUPPRESSED_SECRET_PATTERN]"

# ---------------------------------------------------------------------------
# Artifact filename → subdirectory name mapping
# (flat layout preferred; subdir used as fallback)
# ---------------------------------------------------------------------------
_ARTIFACT_MUTATION_PATCH = "mutation_patch.json"
_ARTIFACT_LEDGER = "api_usage_ledger.json"
_ARTIFACT_CANDIDATE = "candidate_detector.py"
_ARTIFACT_FITNESS = "fitness_report.json"
_ARTIFACT_PROMOTE = "promote_result.json"

_ARTIFACT_SUBDIRS: dict[str, str] = {
    _ARTIFACT_MUTATION_PATCH: "mutation-patch",
    _ARTIFACT_LEDGER: "api-usage-ledger",
    _ARTIFACT_CANDIDATE: "candidate-detector",
    _ARTIFACT_FITNESS: "fitness-report",
    _ARTIFACT_PROMOTE: "promote-result",
}

# Classification values
_CLASS_PROPOSE_FAILED = "propose_failed"
_CLASS_APPLY_FAILED = "apply_failed_or_not_reached"
_CLASS_EVALUATE_REJECTED = "evaluate_rejected"
_CLASS_PROMOTE_ELIGIBLE = "promote_eligible"
_CLASS_PROMOTED = "promoted"
_CLASS_TOOL_FAILURE = "tool_failure"


# ---------------------------------------------------------------------------
# Secret-safe helpers
# ---------------------------------------------------------------------------

def _contains_secret(text: str) -> bool:
    """Return True if text matches any known secret pattern."""
    return any(p.search(text) for p in _SECRET_PATTERNS)


def _safe_text(value: object) -> str:
    """Convert value to str; replace entire string with placeholder if it contains a secret.

    Use this for ALL user-visible dynamic strings: evidence, warnings,
    recommended_next_action fragments, Markdown output, and stdout summaries.
    """
    text = value if isinstance(value, str) else str(value)
    return _SECRET_REPLACEMENT if _contains_secret(text) else text


# ---------------------------------------------------------------------------
# Artifact resolution
# ---------------------------------------------------------------------------

def _resolve_artifact(artifacts_dir: Path, filename: str) -> tuple[Path | None, str]:
    """Find artifact file, trying flat then subdirectory layout.

    Returns (resolved_path_or_None, layout_description).
    layout_description is 'flat', 'subdir:<name>', or 'not_found'.
    """
    flat = artifacts_dir / filename
    if flat.exists():
        return flat, "flat"

    subdir_name = _ARTIFACT_SUBDIRS.get(filename)
    if subdir_name:
        sub = artifacts_dir / subdir_name / filename
        if sub.exists():
            return sub, f"subdir:{subdir_name}"

    return None, "not_found"


# ---------------------------------------------------------------------------
# JSON loading
# ---------------------------------------------------------------------------

def _load_json_safe(path: Path) -> tuple[dict | list | None, str | None]:
    """Load JSON from path.  Return (data, None) on success or (None, error) on failure.

    Never raises.  Returns (None, reason) for missing, empty, or malformed files.
    The error string is safe to include in output (no secret values embedded).
    """
    if not path.exists():
        return None, f"file not found: {path.name}"
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return None, f"{path.name} contains invalid UTF-8 encoding"
    except OSError as exc:
        return None, f"cannot read {path.name}: {type(exc).__name__}"

    if not text.strip():
        return None, f"{path.name} is empty"

    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        return None, f"malformed JSON in {path.name} at line {exc.lineno}"

    return data, None


# ---------------------------------------------------------------------------
# Secret scanning
# ---------------------------------------------------------------------------

def _scan_for_secrets(path: Path | None, filename: str, warnings: list[str]) -> None:
    """Warn (without revealing value) if file appears to contain a secret-pattern string."""
    if path is None or not path.exists():
        return
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return
    if _contains_secret(text):
        warnings.append(
            f"secret-pattern string detected in {filename} — value suppressed"
        )


# ---------------------------------------------------------------------------
# fitness_report normalisation
# ---------------------------------------------------------------------------

def _extract_fitness_payload(report: dict) -> dict | None:
    """Normalise fitness_report.json to a payload containing passed_adoption_gate (bool).

    Handles both:
      flat shape:    {"passed_adoption_gate": bool, "score": float, ...}
      wrapper shape: {"success": bool, "fitness_report": {"passed_adoption_gate": bool, ...}, ...}

    Strategy mirrors the current workflow's `r.get("fitness_report") or r`:
      1. If a nested "fitness_report" key is a dict, use it (has full core.fitness metrics).
      2. Otherwise, use the outer dict.
      3. If the resolved payload has no bool passed_adoption_gate, return None (fail-closed).
    """
    nested = report.get("fitness_report")
    payload: dict = nested if isinstance(nested, dict) else report

    if not isinstance(payload, dict):
        return None

    gate = payload.get("passed_adoption_gate")
    if not isinstance(gate, bool):
        return None

    return payload


# ---------------------------------------------------------------------------
# Main triage logic
# ---------------------------------------------------------------------------

def _triage(artifacts_dir: Path) -> dict:
    """Run the deterministic triage logic and return the result dict."""
    evidence: list[str] = []
    warnings: list[str] = []

    # ------------------------------------------------------------------
    # Artifact resolution (flat preferred; subdir fallback)
    # ------------------------------------------------------------------
    mp_path, mp_layout = _resolve_artifact(artifacts_dir, _ARTIFACT_MUTATION_PATCH)
    ledger_path, ledger_layout = _resolve_artifact(artifacts_dir, _ARTIFACT_LEDGER)
    cand_path, cand_layout = _resolve_artifact(artifacts_dir, _ARTIFACT_CANDIDATE)
    fitness_path, fitness_layout = _resolve_artifact(artifacts_dir, _ARTIFACT_FITNESS)
    promote_path, promote_layout = _resolve_artifact(artifacts_dir, _ARTIFACT_PROMOTE)

    artifacts_seen = {
        "mutation_patch": mp_path is not None,
        "api_usage_ledger": ledger_path is not None,
        "candidate_detector": cand_path is not None,
        "fitness_report": fitness_path is not None,
        "promote_result": promote_path is not None,
    }

    # Record resolved layouts in evidence (safe: layout strings contain no secrets)
    for name, path, layout in [
        ("mutation_patch.json", mp_path, mp_layout),
        ("api_usage_ledger.json", ledger_path, ledger_layout),
        ("candidate_detector.py", cand_path, cand_layout),
        ("fitness_report.json", fitness_path, fitness_layout),
        ("promote_result.json", promote_path, promote_layout),
    ]:
        if path is not None:
            evidence.append(f"{name} found ({layout})")

    # Scan all present artifacts for secrets before reading values
    for path, filename in [
        (mp_path, _ARTIFACT_MUTATION_PATCH),
        (ledger_path, _ARTIFACT_LEDGER),
        (cand_path, _ARTIFACT_CANDIDATE),
        (fitness_path, _ARTIFACT_FITNESS),
        (promote_path, _ARTIFACT_PROMOTE),
    ]:
        _scan_for_secrets(path, filename, warnings)

    # ------------------------------------------------------------------
    # Stage 1 — propose: was a valid mutation patch produced?
    # policy: malformed patch → propose_failed + warning (not tool_failure)
    # ------------------------------------------------------------------
    mutation_patch_produced = False
    if artifacts_seen["mutation_patch"] and mp_path is not None:
        mp_data, mp_err = _load_json_safe(mp_path)
        if mp_data is not None:
            mutation_patch_produced = True
            evidence.append("mutation_patch.json parsed successfully")
        else:
            warnings.append(f"mutation_patch.json parse error: {mp_err}")
            evidence.append("mutation_patch.json present but malformed — propose_failed")
    else:
        evidence.append("mutation_patch.json absent — propose stage did not produce a patch")

    # Check api_usage_ledger for API success evidence (read-only, safe field extraction)
    if artifacts_seen["api_usage_ledger"] and ledger_path is not None:
        ledger_data, ledger_err = _load_json_safe(ledger_path)
        if ledger_data is not None:
            if isinstance(ledger_data, list) and ledger_data:
                last = ledger_data[-1]
                if isinstance(last, dict):
                    # Route all field values through _safe_text before emitting
                    safe_model = _safe_text(last.get("model", "unknown"))
                    safe_mode = _safe_text(last.get("api_mode", "unknown"))
                    safe_success = _safe_text(str(last.get("success")))
                    evidence.append(
                        f"api_usage_ledger last record: model={safe_model} "
                        f"api_mode={safe_mode} success={safe_success}"
                    )
            else:
                evidence.append("api_usage_ledger.json present but contains no records")
        else:
            warnings.append(f"api_usage_ledger.json parse error: {ledger_err}")
    else:
        evidence.append("api_usage_ledger.json absent from artifacts dir")

    # ------------------------------------------------------------------
    # Stage 2 — apply: was the candidate file written?
    # ------------------------------------------------------------------
    apply_reached = artifacts_seen["candidate_detector"]
    if apply_reached:
        evidence.append("candidate_detector.py present — apply stage reached")
    else:
        evidence.append(
            "candidate_detector.py absent — apply stage not reached (or failed)"
        )

    # ------------------------------------------------------------------
    # Stage 3 — evaluate: was fitness_report.json written and parseable?
    # policy: malformed or unexpected payload → tool_failure (fail-closed)
    # ------------------------------------------------------------------
    evaluate_reached = artifacts_seen["fitness_report"]

    adoption_gate_passed: bool | None = None
    fitness_tool_failure = False
    fitness_rejection_reasons: list[str] = []

    if evaluate_reached and fitness_path is not None:
        evidence.append("fitness_report.json present — evaluate stage reached")
        fitness_data, fitness_err = _load_json_safe(fitness_path)

        if fitness_data is None:
            warnings.append(
                f"fitness_report.json parse failed (fail-closed): {fitness_err}"
            )
            fitness_tool_failure = True
            evidence.append("fitness_report.json malformed — classified as tool_failure")

        elif not isinstance(fitness_data, dict):
            warnings.append(
                "fitness_report.json root is not a JSON object (fail-closed)"
            )
            fitness_tool_failure = True
            evidence.append(
                "fitness_report.json has unexpected root type — classified as tool_failure"
            )

        else:
            # Normalise: handle both flat and evaluator-wrapper shapes
            payload = _extract_fitness_payload(fitness_data)

            if payload is None:
                # passed_adoption_gate missing or not a bool — fail closed
                raw_gate = fitness_data.get("passed_adoption_gate")
                nested = fitness_data.get("fitness_report")
                if isinstance(nested, dict):
                    raw_gate = nested.get("passed_adoption_gate")
                # Emit the TYPE, not the value, to avoid leaking secrets
                gate_type = type(raw_gate).__name__
                warnings.append(
                    f"passed_adoption_gate has unexpected type {gate_type!r} — fail-closed"
                )
                fitness_tool_failure = True
                evidence.append(
                    f"passed_adoption_gate type={gate_type!r} — unexpected, treating as tool_failure"
                )

            else:
                gate_val = payload["passed_adoption_gate"]  # guaranteed bool by _extract_fitness_payload

                if gate_val is True:
                    adoption_gate_passed = True
                    evidence.append("passed_adoption_gate=true")
                else:
                    adoption_gate_passed = False
                    evidence.append("passed_adoption_gate=false")

                # Collect rejection reasons — route each through _safe_text
                raw_reasons = payload.get("rejection_reasons")
                if isinstance(raw_reasons, list):
                    for r in raw_reasons:
                        if isinstance(r, str):
                            fitness_rejection_reasons.append(_safe_text(r))
                    if fitness_rejection_reasons:
                        evidence.append(
                            "rejection_reasons: "
                            + "; ".join(fitness_rejection_reasons[:5])
                        )

                # Score and rate fields (numeric only — safe)
                score_val = payload.get("score")
                if isinstance(score_val, (int, float)):
                    evidence.append(f"fitness score={float(score_val)}")

                for rate_field in ("tp_rate", "fp_rate", "fn_rate"):
                    val = payload.get(rate_field)
                    if isinstance(val, (int, float)):
                        evidence.append(f"{rate_field}={val}")

                # candidate_hash (safe hex string only)
                chash = payload.get("candidate_hash")
                if isinstance(chash, str) and re.match(r"^[0-9a-f]{64}$", chash):
                    evidence.append(f"candidate_hash={chash[:16]}...")

    else:
        evidence.append("fitness_report.json absent — evaluate stage not reached")

    # ------------------------------------------------------------------
    # Stage 4 — promote: was promote_result.json written?
    # NOTE: The current immunization_loop.yml does NOT emit this artifact.
    # This classification is future-reserved.
    # ------------------------------------------------------------------
    promote_reached = artifacts_seen["promote_result"]
    if promote_reached:
        evidence.append(
            "promote_result.json present — promote stage reached "
            "(note: current workflow does not generate this artifact)"
        )
    else:
        evidence.append("promote_result.json absent — promote stage not reached")

    # ------------------------------------------------------------------
    # Classification logic (deterministic, fail-closed)
    # ------------------------------------------------------------------
    classification: str
    recommended_next_action: str
    requires_owner_approval: bool

    if fitness_tool_failure:
        classification = _CLASS_TOOL_FAILURE
        recommended_next_action = (
            "fitness_report.json could not be parsed or its gate field was invalid. "
            "Inspect the raw artifact for corruption. "
            "Re-download the artifact and re-run triage, or diagnose the evaluate job logs."
        )
        requires_owner_approval = False

    elif promote_reached:
        # future-reserved: promote_result.json present
        classification = _CLASS_PROMOTED
        recommended_next_action = (
            "promote_result.json is present. "
            "Verify data/genome.json and data/api_usage_ledger.json were updated correctly. "
            "Run pytest tests/test_project_state_sync.py to confirm state sync. "
            "(Note: this artifact is not generated by the current workflow; "
            "verify it was produced by a future-generation promote step.)"
        )
        requires_owner_approval = True

    elif evaluate_reached and adoption_gate_passed is True:
        classification = _CLASS_PROMOTE_ELIGIBLE
        recommended_next_action = (
            "Candidate passed adoption gate. "
            "Project Owner must review the fitness report and decide the next promotion process. "
            "The current standard workflow promotes only within the same run when "
            "promote_approved=true; this local tool does not promote and does not preserve "
            "a promotion-capable artifact handoff."
        )
        requires_owner_approval = True

    elif evaluate_reached and adoption_gate_passed is False:
        classification = _CLASS_EVALUATE_REJECTED
        if fitness_rejection_reasons:
            reason_str = "; ".join(fitness_rejection_reasons)
        else:
            reason_str = "see rejection_reasons in fitness_report.json"
        recommended_next_action = (
            f"Candidate failed adoption gate: {reason_str}. "
            "Inspect rejection_reasons and fitness metrics. "
            "Open a new propose-side pre-screen PR to address the rejection pattern, "
            "then request a new Owner-approved rerun."
        )
        requires_owner_approval = False

    elif apply_reached and not evaluate_reached:
        classification = _CLASS_APPLY_FAILED
        recommended_next_action = (
            "apply stage produced candidate_detector.py but evaluate was not reached. "
            "Inspect the evaluate job logs for the failing policy check or AST violation. "
            "Open a propose-side pre-screen PR to address the gap, "
            "then request a new Owner-approved rerun."
        )
        requires_owner_approval = False

    elif mutation_patch_produced and not apply_reached:
        classification = _CLASS_APPLY_FAILED
        recommended_next_action = (
            "mutation_patch.json was produced but apply did not write candidate_detector.py. "
            "Inspect the apply step logs for policy check failures (e.g. repeat-multiplier). "
            "Open a propose-side pre-screen PR to address the constraint, "
            "then request a new Owner-approved rerun."
        )
        requires_owner_approval = False

    else:
        classification = _CLASS_PROPOSE_FAILED
        recommended_next_action = (
            "mutation_patch.json was not produced or was malformed. "
            "Inspect propose job logs and api_usage_ledger.json. "
            "If the API call succeeded but the patch was rejected by output-contract checks, "
            "review the propose-side output-contract hardening (PR #84 / #91). "
            "Request a new Owner-approved rerun."
        )
        requires_owner_approval = False

    # ------------------------------------------------------------------
    # Assemble stage_status
    # ------------------------------------------------------------------
    stage_status = {
        "mutation_patch_produced": mutation_patch_produced,
        "apply_reached": apply_reached,
        "evaluate_reached": evaluate_reached,
        "adoption_gate_passed": adoption_gate_passed,
        "promote_reached": promote_reached,
    }

    return {
        "schema_version": _SCHEMA_VERSION,
        "artifacts_dir": str(artifacts_dir),
        "artifacts_seen": artifacts_seen,
        "stage_status": stage_status,
        "decision": {
            "classification": classification,
            "recommended_next_action": recommended_next_action,
            "requires_owner_approval": requires_owner_approval,
        },
        "evidence": evidence,
        "warnings": warnings,
    }


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------

def _render_markdown(result: dict) -> str:
    """Render a Markdown summary of the triage result.

    All dynamic strings are already secret-safe by the time they appear in
    the result dict (every value passed through _safe_text() during triage).
    """
    d = result["decision"]
    ss = result["stage_status"]
    lines = [
        "# S4 Rerun Triage Summary",
        "",
        f"**Classification:** `{d['classification']}`",
        f"**Requires Owner Approval:** {d['requires_owner_approval']}",
        "",
        "## Recommended Next Action",
        "",
        d["recommended_next_action"],
        "",
        "## Stage Status",
        "",
        "| Stage | Reached |",
        "|---|---|",
        f"| propose (mutation_patch_produced) | {ss['mutation_patch_produced']} |",
        f"| apply | {ss['apply_reached']} |",
        f"| evaluate | {ss['evaluate_reached']} |",
        f"| adoption_gate_passed | {ss['adoption_gate_passed']} |",
        f"| promote | {ss['promote_reached']} |",
        "",
        "## Artifacts Seen",
        "",
    ]
    for name, seen in result["artifacts_seen"].items():
        mark = "✓" if seen else "✗"
        lines.append(f"- {mark} {name}")
    lines.append("")

    if result["evidence"]:
        lines.append("## Evidence")
        lines.append("")
        for e in result["evidence"]:
            lines.append(f"- {e}")
        lines.append("")

    if result["warnings"]:
        lines.append("## Warnings")
        lines.append("")
        for w in result["warnings"]:
            lines.append(f"- ⚠ {w}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Deterministic local triage for S4 rerun artifacts.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--artifacts-dir",
        required=True,
        metavar="DIR",
        help="Directory containing downloaded S4 rerun artifacts.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="output_json",
        help="Print triage result as JSON to stdout.",
    )
    parser.add_argument(
        "--markdown",
        metavar="PATH",
        default=None,
        help="Write a Markdown summary to this file path.",
    )
    args = parser.parse_args(argv)

    artifacts_dir = Path(args.artifacts_dir).resolve()
    if not artifacts_dir.exists():
        print(
            json.dumps({
                "schema_version": _SCHEMA_VERSION,
                "error": f"artifacts_dir does not exist: {artifacts_dir}",
                "classification": _CLASS_TOOL_FAILURE,
            }),
            file=sys.stderr,
        )
        return 2

    result = _triage(artifacts_dir)

    if args.output_json:
        print(json.dumps(result, indent=2))
    else:
        d = result["decision"]
        print(f"Classification : {d['classification']}")
        print(f"Requires Owner : {d['requires_owner_approval']}")
        print(f"Next action    : {d['recommended_next_action']}")
        if result["warnings"]:
            print("\nWarnings:")
            for w in result["warnings"]:
                print(f"  ! {w}")

    if args.markdown:
        md_path = Path(args.markdown)
        md_path.parent.mkdir(parents=True, exist_ok=True)
        md_path.write_text(_render_markdown(result), encoding="utf-8")
        print(f"\nMarkdown summary written to {md_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
